---
# tasks file for install_nginx

- include_role:
    name: epel

- name: install nginx
  yum:
    name: nginx
    state: present

- name: create /var/www/html
  file:
    path: /var/www/html
    state: directory
    owner: nginx
    group: nginx
    mode: 0755
